name: Release on PR or commit 
on:
  pull_request:
    types:
      - closed
    branches: [ "master" ]
    paths-ignore:
      - 'readme.md'
      - 'docs/**/*'
      - '.github/**/*'

jobs:
  build:
    if: github.repository == 'dbuezas/lgt8fx' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=$(node make.js)" >> $GITHUB_ENV
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
    - uses: ncipollo/release-action@v1
      with:
        tag: "v${{env.RELEASE_VERSION}}"
        artifacts: "lgt8f-${{env.RELEASE_VERSION}}.zip"
